name: Lab Sector8
favicon: null
layout_spectrum: 0.5794517467729747
typography_spectrum: 0.3351453854702413
title: Lab Sector8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4f4f4f'
    - '#c8c8c8'
    - '#948c84'
  brandStrength: 0.8065055671613663
  lightness: 0.3466318715363741
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
